DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS Classification CASCADE;
DROP TABLE IF EXISTS AccountClassification CASCADE;
DROP TABLE IF EXISTS TaskClassification CASCADE;
